# Generated by Django 3.2.7 on 2021-10-02 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_auto_20210904_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_modified',
        ),
    ]
