# Generated by Django 3.2.7 on 2021-10-02 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_remove_post_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.tag'),
        ),
    ]
